### ISSUE TITLE
Android Home widget

### ISSUE THREAD

**Issue by F2had** [NedaaDevs/nedaa#52]

**Comment by burhanaksendir** [comment]
There's an issue with the home widget. Even though it's past Dhuhr prayer time, the countdown isn't resetting; it's progressing forward instead. The expected behavior was for the countdown to reset to 00:00 when it transitions to the next prayer time. It seems like the home widget isn't updating properly at the correct times. I'm attaching a video for reference.

https://github.com/NedaaDevs/nedaa/assets/8548639/5103693c-dd96-4d52-b884-9dad3e215ad9

**Comment by F2had** [comment]
> There's an issue with the home widget. Even though it's past Dhuhr prayer time, the countdown isn't resetting; it's progressing forward instead. The expected behavior was for the countdown to reset to 00:00 when it transitions to the next prayer time. It seems like the home widget isn't updating properly at the correct times. I'm attaching a video for reference.
> 
> 
> 
> https://github.com/NedaaDevs/nedaa/assets/8548639/5103693c-dd96-4d52-b884-9dad3e215ad9
> 
> 
> 
> 

@burhanaksendir 
This behavior is actually intended.
So the idea is:
1- Show the next prayer time
2- An hour before the prayer starts a countdown.
3- Count up 30min after the prayer (just to know how long since the Athan)
4- 30min after the prayer show the next prayer time.

If you would like to disable the timer you can do so using the widget settings. ![image](https://github.com/NedaaDevs/nedaa/assets/42780409/e86a8a2e-aacd-4662-8f70-2c8ec898cc22)

**Comment by burhanaksendir** [comment]
> > There's an issue with the home widget. Even though it's past Dhuhr prayer time, the countdown isn't resetting; it's progressing forward instead. The expected behavior was for the countdown to reset to 00:00 when it transitions to the next prayer time. It seems like the home widget isn't updating properly at the correct times. I'm attaching a video for reference.
> > 
> >   
> >     
> >     
> > 
> >     widget.mp4
> 
> @burhanaksendir This behavior is actually intended. So the idea is: 1- Show the next prayer time 2- An hour before the prayer starts a countdown. 3- Count up 30min after the prayer (just to know how long since the Athan) 4- 30min after the prayer show the next prayer time.
> 
> If you would like to disable the timer you can do so using the widget settings. ![image](https://private-user-images.githubusercontent.com/42780409/341978012-e86a8a2e-aacd-4662-8f70-2c8ec898cc22.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNjg0MTcsIm5iZiI6MTcxOTA2ODExNywicGF0aCI6Ii80Mjc4MDQwOS8zNDE5NzgwMTItZTg2YThhMmUtYWFjZC00NjYyLThmNzAtMmM4ZWM4OThjYzIyLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMlQxNDU1MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMmM1NGVmNzEwYTlkMTcxN2ZjNjI2MzllMDJhNTU0MmFhZDZjM2VhYzc4NDFlZDliMmE0OWRiMzJmZGY2YjEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5-E6E_rCbK122tQFni7W7cuuuonWilymBKqd6bJa45g)

Thank you very much for your detailed explanation.
